### ISSUE TITLE
New coin alert?

### ISSUE THREAD

**Issue by blademckain** [beeb/pancaketrade#1]
Hi, 
congratulations, great job!
I was wondering if it might be interesting to add a monitor to search for new tokens just placed on the pancakeswap market with an alert on the bot and the ability to buy them immediately

**Comment by beeb** [comment]
Hi! thanks for publishing the first issue on this repo! 
This is an interesting idea but I feel like BSC is plagued with a lot of scams and there are new tokens literally every minute (see [poocoin](https://poocoin.app/ape)).

**Comment by blademckain** [comment]
yes, you are right about scams, 
maybe it would be possible to adopt some logic (market cap overt time, numbers of holder over time) in order to identify profitable tokens

**Comment by beeb** [comment]
I feel like this would be a topic for completely separate bot/system. There's a number of factors to take into account when doing research on a new token launch, from contract source code to supply repartition, liquidity locks, dev team identity etc etc. Not something I'm willing to dip my toes into, and maybe not even something can that can be automated. I'll close for now, thanks for contributing!
