### ISSUE TITLE
Github Docker Workflow failing

### ISSUE THREAD

**Issue by DigiTecK3D** [beeb/pancaketrade#10]
Wondering, I'm doing submissions and noticing the docker is giving a username and error, never seen it before. was this cause of me forking or something. I honestly have never messed with docker or GitHub workflows before. Thanks!

![image](https://user-images.githubusercontent.com/5471872/121632506-b8177a80-ca46-11eb-9aa5-357868746489.png)

**Comment by beeb** [comment]
Yeah you did not setup your workflow for docker so you can just delete that yaml file altogether. Or setup some credentials for docker hub if you want to build images for your fork.
