### ISSUE TITLE
Error at running the bot

### ISSUE THREAD

**Issue by jaillela** [beeb/pancaketrade#37]
I am having the following problem when I execute the command: poetry run trade
Any ideas how to sort this out? 
Thanks a lot!!
Python Version 3.9.
![Captura de pantalla 2021-10-29 223854](https://user-images.githubusercontent.com/49876939/139499025-24e99456-971d-4f6b-bfeb-a9df3ebe9c47.png)

**Comment by beeb** [comment]
Did you install the dependencies?

**Comment by jaillela** [comment]
I did install CLICK, LOGORU and TELEGRAM. 
Am I missing any other dependencies?
Thanks!

**Comment by jaillela** [comment]
Also, the funny thing is, that when running indiviudally each of the .py codes on IDEL Shell, the only module missing by the terminal is "pancaketrade"

![image](https://user-images.githubusercontent.com/49876939/139507873-bcac408e-cb88-40dd-a8af-e4cd7ca0dedc.png)

**Comment by beeb** [comment]
You probably didn't read the instructions. This project is using poetry to manage dependencies so you need to run `poetry install`
