### ISSUE TITLE
Different LPs on Pancake

### ISSUE THREAD

**Issue by yocovn** [beeb/pancaketrade#39]
Hi,
First of all, nice job on the bot.
One question I have is: is it possible to support different LP on the pancake swap? (maybe a silly question)
Also, I'm not very sure, but I think for example MTV/BNB and MTV/USDT are different LP for a single coin? (see screen)

Proposal: when you add a coin you can select which LP to use.

**Comment by vbersier** [comment]
Hello,

Please refer to the release notes at https://github.com/beeb/pancaketrade/releases/tag/v0.6.0

Currently BNB and BUSD are automatically supported and the best price is used. Do you wish to support USDT too?

**Comment by beeb** [comment]
Hello,

Please refer to the release notes at https://github.com/beeb/pancaketrade/releases/tag/v0.6.0

Currently BNB and BUSD are automatically supported and the best price is used. Do you wish to support USDT too?

**Comment by yocovn** [comment]
Hi,
Thanks for the reference. 
Yes, please Tether USD on Bep20 would be very useful. Because, for example for MTV coin has about $800 in MTV/BNB LP and around $145000 in MTV/USDT LP. So, for this coin makes no sense to use the MTV/BNB pool as it will drain if you sell ...
Again, great work. (I'm using it in a docker, works perfectly)

**Comment by beeb** [comment]
Gotcha, I will add it to the develop branch and test for a while. Feel free to test as well, if you know the risks involved.

**Comment by yocovn** [comment]
Thanks. I will. Please let me know when you build an image, so I can pull from the docker artifactory.

**Comment by beeb** [comment]
Ok the develop branch has been updated, there is a new docker image for `develop` which includes USDT
https://hub.docker.com/layers/vbersier/pancaketrade/develop/images/sha256-cc887a4b4482457810c8e1456f562d214fd90ea34a9b6186ada63e5c63da7a23?context=repo

**Comment by yocovn** [comment]
Will it take decision only based on the price? 
For example: 
MTV/BNB price: 0.024 per MTV (LP $800)
MTV/USDT price: 0.023 per MTV (LP $140000)

So, if I would see $1000 worth of MTV will that still go against the MTV/BNB LP assuming the price there is better?

If so, there may be a problem as the LP will not be enough.

**Comment by beeb** [comment]
Yes the price will be compared and the best path (that leads to the highest output) will be used. This price comparison takes into account the liquidity size (price impact) and pancakeswap fee, so it's not a problem that the liquidity is small.

**Comment by beeb** [comment]
Example with MTV. The bot will compare the two paths:

- MTV -> BNB
    Input 50'000 MTV -> output  0.935 BNB
- MTV -> USDT -> BNB
    Input 50'000 MTV -> output 2.214 BNB
