### ISSUE TITLE
"Buy/Sell now" hangs

### ISSUE THREAD

**Issue by ssergiio** [beeb/pancaketrade#50]
**Please confirm the following**
- [x] I am on the latest stable [release](https://github.com/beeb/pancaketrade/releases) of `pancaketrade`
- [x] I have searched the [issues](https://github.com/beeb/pancaketrade/issues) and cannot find a similar one
- [x] I have read the entire Readme and followed all installation instructions

**Setup (please complete the following information):**
 - OS and version: Raspbian 10
 - Pancaketrade version: 0.6.1

**Describe the bug**
Sometimes when you try to use the "Buy/Sell now" function and select the token you want to buy or sell, it just hangs with the loading wheel and stops (times out) after some seconds. Only workaround I found so far is to restart the service and it works again.

**To Reproduce**
1. Click on "Buy/Sell now" button
2. Click on the desired token
3. It hangs (but it only happens sometimes, it normally works)

**Expected behavior**
It should continue to ask details (amount to be bought/sell.. etc) just like when it works as expected.

**Screenshots**
Don't have ATM but I will post them as soon as it happens to me again.

**Additional context**
As I said it's an occasional problem, not happens every time. But when it happens it forces you to restart the service.

**Comment by beeb** [comment]
I've had this happen in the past which seemed to be a telegram problem. If the python logs don't show an error, you could try to generate a new telegram bot token and use that one instead

**Comment by ssergiio** [comment]
I'll try, I have to say it didn't happened to me again after submitting the bug haha murphy. Also: decreasing the 30s between /status messages updates could cause troubles?

Thanks for your work!

**Comment by beeb** [comment]
>  decreasing the 30s between /status messages updates could cause troubles?

Oh yes that might be a problem! If you send message updates too often to Telegram, it might flag your account for sending too many requests and it might cause the API to fail. Please don't decrease this value, telegram doesn't like it, they have limits in place but we don't know the exact values.
