### ISSUE TITLE
received a message "Prevented user 842900455 to interact" . is someone trying to hack?

### ISSUE THREAD

**Issue by Asifadb** [beeb/pancaketrade#51]
hi received a message "Prevented user 842900455 to interact"

is now my pk is safe? my funds are safe?

thanks

**Please confirm the following**
- [ ] I am on the latest stable [release](https://github.com/beeb/pancaketrade/releases) of `pancaketrade`
- [ ] I have searched the [issues](https://github.com/beeb/pancaketrade/issues) and cannot find a similar one
- [ ] I have read the entire Readme and followed all installation instructions

**Setup (please complete the following information):**
 - OS and version: 
 - Pancaketrade version: 

**Describe the bug**

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beeb** [comment]
Bots cannot be private on Telegram, which is why you must enter your user ID in the config file. The bot takes care to block out any person that is not you. Your funds are safe.
