### ISSUE TITLE
receiving this warning : connection pool is full, discarding connection: bsc-dataseed.binance.org.

### ISSUE THREAD

**Issue by Asifadb** [beeb/pancaketrade#57]
receiving this warning : connection pool is full, discarding connection: bsc-dataseed.binance.org.

Receiving after changing nodes even with getblock.io node.

Help is appreciated. Thanx

**Please confirm the following**
- [x] I am on the latest stable [release](https://github.com/beeb/pancaketrade/releases) of `pancaketrade`
- [x] I have searched the [issues](https://github.com/beeb/pancaketrade/issues) and cannot find a similar one
- [x] I have read the entire Readme and followed all installation instructions

**Setup (please complete the following information):**
 - OS and version: 
 - Pancaketrade version: 

**Describe the bug**

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beeb** [comment]
This is a warning only, It's not a bug. It means that you are trying to have too many open connections to the RPC. This is most likely due to a slow RPC or too frequent price update (less than 5 seconds) or too many tokens in the list.
