### ISSUE TITLE
[Error] poetry run trade 

### ISSUE THREAD

**Issue by ivanbouwmeester** [beeb/pancaketrade#62]
Hi, I followed all the instructions in the readme document I am working in WSL, I have python 3.7.1 and poetry 11.1.1 but I am keeping this error message: The virtual environment found in /mnt/c/users/ivan/desktop/pancaketrade-master 1/.venv seems to be broken.
Recreating virtualenv pancaketrade in /mnt/c/users/ivan/desktop/pancaketrade-master 1/.venv (see the attached file for full error message)

Does anyone have any solutions? 
![error](https://user-images.githubusercontent.com/94984911/143286955-d16d229f-7e69-4f5d-9c71-d62eb78e2a3f.png)

**Comment by beeb** [comment]
Try to store all the files inside the WSL storage. You are currently accessing files on your Windows drive

**Comment by ivanbouwmeester** [comment]
Yep, that was the error. Thanks boss +1
