### ISSUE TITLE
Re connecting

### ISSUE THREAD

**Issue by ivanbouwmeester** [beeb/pancaketrade#63]
Everything worked fine until I decided to close the running script in WSL, Now when I enter poetry run bot it gives the error: ''Config file does not exist at /home/ivanbouwmeester/pancaketrade/pancaketrade/user_data/config.yml''

The config file is still the same as before, do I have to make a new TG bot or something to connect it again?

**Comment by beeb** [comment]
Check that the file exists at that location and that the permissions are set correctly on the file.

**Comment by osatien** [comment]
Perhaps permissions .... Can you give 777 to dir and files

**Comment by beeb** [comment]
Close due to inactivity and probable cause being permissions
