### ISSUE TITLE
connection failed

### ISSUE THREAD

**Issue by wq0828** [beeb/pancaketrade#64]
I'm in a country that doesn't support telegrams, so I use a proxy to surf the Internet, but the python library can't be connected. What should I do
![1637925983(1)](https://user-images.githubusercontent.com/83150540/143574280-36ec4793-c002-4c43-86f5-6d66a12d40f3.jpg)

**Comment by beeb** [comment]
Try not using windows?

**Comment by osatien** [comment]
Perhaps setting the proxy could help.
In windows should be set HTTP_PROXY="http://Ip:port"

**Comment by osatien** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy

It should work with https_proxy

**Comment by beeb** [comment]
Stale
