### ISSUE TITLE
Token price update broken

### ISSUE THREAD

**Issue by DigiTecK3D** [beeb/pancaketrade#7]
Seems with the total wallet addition in the code on submitting 3d17907eedead2c0ccabd4baf7d999e12b859f77 the telegram bot used to auto-refresh the prices on the status page and on merging change it won't work again and after I discard changes it works again.

**Comment by beeb** [comment]
Nice catch, I forgot to modify the logic for the update function. Fix incoming

**Comment by beeb** [comment]
Fixed in https://github.com/beeb/pancaketrade/releases/tag/v0.4.2
