### ISSUE TITLE
docker run  error

### ISSUE THREAD

**Issue by geeks121** [beeb/pancaketrade#72]
i want to deploy the app in azure app service but when i build with docker file and try to run i'm facing error ,,

```
2021-12-16 02:38:09  ERROR  |Config file does not exist at /app/user_data/config.yml
2021-12-16 02:38:09   INFO  |Bye!
```

i can't run docker-compose or docker compose in azure app service ,,

**Comment by beeb** [comment]
I have not tested this in azure but if you make sure to provide the config file in the path mentioned in the error message it should work. Read the error message and act accordingly

**Comment by geeks121** [comment]
yes i rechecked that file ,, and config file ,,, it exist but when i run with command : docker run -d
the error is on the above ,, and if i run with docker-compose up -d
the bot work ,, 
that's is strange for me

**Comment by beeb** [comment]
> 

please read the documentation for `docker run` https://docs.docker.com/engine/reference/run/
you can achieve a similar result as with docker-compose but you need to add all the relevant arguments for binding etc.
