### ISSUE TITLE
Can't get gas estimate, cancelling transaction: execution reverted: PancakeRouter: INSUFFICIENT_OUTPUT_AMOUNT

### ISSUE THREAD

**Issue by 41v4** [beeb/pancaketrade#88]
**Please confirm the following**
- [x] I am on the latest stable [release](https://github.com/beeb/pancaketrade/releases) of `pancaketrade`
- [x] I have searched the [issues](https://github.com/beeb/pancaketrade/issues) and cannot find a similar one
- [x] I have read the entire Readme and followed all installation instructions

**Setup (please complete the following information):**
 - OS and version: Ubuntu 20.04
 - Pancaketrade version: v0.6.2

**Describe the bug**
It fails to execute an order because (I guess) it fails to estimate the gas limit

network/bsc.py:
```
try:
    gas_limit = Wei(int(Decimal(func.estimateGas({'from': self.wallet, 'value': amount_bnb})) * Decimal(1.2)))
except Exception as e:
    logger.error(f'Can\'t get gas estimate, cancelling transaction: {e}')
    return None
```

**To Reproduce**
1. Token address: 0xdFE6891ce8E5a5c7Cf54fFdE406A6C2C54145F71
2. Amount: 0.006 BNB
3. Price: < 1.14e-17
4. Slippage: 5.00%
5. Gas: network default +2 Gwei

**Expected behavior**
I expect to buy a token

**Screenshots**
![estimateGas](https://user-images.githubusercontent.com/42656508/156731180-87b98dcc-65d4-42be-b6f7-86193126d729.png)
![terminal](https://user-images.githubusercontent.com/42656508/156731801-9554bbc3-22f1-4f48-b301-2a5e311637da.png)

**Additional context**
None

**Comment by 41v4** [comment]
It seems the 5% slippage was too low. I have tried with 15% slippage and it went ok.

**Comment by beeb** [comment]
Yep when in doubt, refer to the pancakeswap documentation. All error messages are described.
