### ISSUE TITLE
Price impact

### ISSUE THREAD

**Issue by spectrumpac** [beeb/pancaketrade#89]
The price impact does not change it always set to 5%

**Comment by spectrumpac** [comment]
I am making something is there a way to disable price impact?

**Comment by beeb** [comment]
I don't understand your request. The price impact is calculated before the trade from the available liquidity and the size of your order. It is not always 5%. The limit above which an order will not execute is by default 5% but it can be customized with the config file. Please describe what is your problem or bug and use the issue template: https://github.com/beeb/pancaketrade/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by spectrumpac** [comment]
It was my bad, I already custumized in the config file, thanks
