### ISSUE TITLE
Config monitor interval

### ISSUE THREAD

**Issue by DigiTecK3D** [beeb/pancaketrade#9]
I noticed an issue when you change the monitor_interval in the config file to 1 the bot crashes and gives a typerror `  File "C:\Users\migue\Documents\GitHub\pancaketrade\.venv\lib\site-packages\apscheduler\job.py", line 196, in _modify
    raise TypeError('misfire_grace_time must be either None or a positive integer')
TypeError: misfire_grace_time must be either None or a positive integer` 

![image](https://user-images.githubusercontent.com/5471872/121295169-3394f280-c8b4-11eb-85e7-8293eae0670e.png)

**Comment by beeb** [comment]
Hey, thanks for catching this! It's an easy fix, I'll look into it today

**Comment by DigiTecK3D** [comment]
Sounds great! Thank you!

**Comment by beeb** [comment]
Should be fixed in https://github.com/beeb/pancaketrade/commit/c975d1060cdb6474cb317e12b7d68f8f6d68c15b

Will test soon

**Comment by DigiTecK3D** [comment]
Perfect, I’ll grab the change and test it out! Thanks again!

**Comment by DigiTecK3D** [comment]
Pulled the changed and tested it, everything is working fine. Thanks for the fix!

**Comment by DigiTecK3D** [comment]
not sure if this has anything to do with the interval thing, but got this from testing a buy right now. 
![image](https://user-images.githubusercontent.com/5471872/121460691-ffccd200-c972-11eb-9e56-eefccda69e01.png)

**Comment by beeb** [comment]
This is expected from smaller intervals, as it might take more than 1 second to check the price of the token. It skips iterations when a job is already running.
