### ISSUE TITLE
Adding unit tests?

### ISSUE THREAD

**Issue by sinancetinkaya** [beeb/pancaketrade#94]
- [X] I have searched the [issues](https://github.com/beeb/pancaketrade/issues) of this repo and believe that this is not a duplicate.
- [X] I have read the Readme and believe that my question is not covered.

## Feature Request

I tried to write my own a DeFi bot but I failed because testing the code with BSC testnet was not working. 
Forking mainnet in Ganache, Hardhat was also problematic.
LP pairs on testnets were always giving weird errors.

How do you test your code?
Would you like to share your unit tests (if any)?

**Comment by beeb** [comment]
Hey there!

No unit tests exist (yet). I don't feel like adding them would bring much value at the moment as the bot has been pretty battle-tested (by me) but I'd be happy to consider a PR.

Good luck for your own bot!

**Comment by sinancetinkaya** [comment]
Thanks for replying back. Do you test your code with real money on the mainnet?
Have you ever tried to use the testnet?

**Comment by beeb** [comment]
I test with real money on mainnet but setting it up for testnet is as simple as changing the RPC url to one of the testnet ones.

**Comment by sinancetinkaya** [comment]
I tried and got similar errors. I think testnet has some weird problems with LP.

**Comment by beeb** [comment]
I edited my comment to mention you need to change the factory and router addresses in the code

**Comment by beeb** [comment]
I guess the stablecoin addresses also needs updating if you're not dealing with BNB LPs. Here are some addresses you can use: https://bsc.kiemtienonline360.com/

**Comment by sinancetinkaya** [comment]
Yes I know they are different on the testnet. I'll give it a try again. I might have forgotten to change one of these 👍
