### ISSUE TITLE
Connection pool size: 20

### ISSUE THREAD

**Issue by morpheusawait** [beeb/pancaketrade#98]
Hello king! Me again.

I have the following warning:

WARNING |Connection pool is full, discarding connection: bsc-dataseed1.binance.org. Connection pool size: 20

I found the line of code so I can modify it but before doing so I would like to know why you chose this limit and what are the simultaneous connections that the bot is activating so I can maybe reduce them.
However, beyond this warning, I don't see how it could be affecting the bot's performance.

Greetings and thanks!

**Comment by beeb** [comment]
I didn't choose it, it's probably the default used by web3.py for the http transport. It means your requests are sent more often than they can be resolved, so either your monitor interval is too short or your connection is slow/unreliable, or maybe both.
